### ISSUE TITLE
Minify error

### ISSUE THREAD

**Issue by Gibson10** [MetaMask/eth-json-rpc-filters#13]
Hello
Am facing an issue when i run a build on my react app

Failed to minify the code from this file: 

 	./node_modules/eth-json-rpc-filters/hexUtils.js:3 

Read more here: http://bit.ly/2tRViJ9

**Comment by mcmire** [comment]
This is an old issue, so I'm closing this, but feel free to respond if you are still experiencing this and I'll reopen it. Thanks!
