### ISSUE TITLE
Why do we pad uneven length hex numbers with leading zeros?

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/eth-json-rpc-filters#152]
Can anyone tell me why?
https://github.com/MetaMask/eth-json-rpc-filters/blob/main/hexUtils.js#L55

This is causing tests against https://github.com/ethereum/execution-apis to fail (expects hex number that is not zero-leading)

**Comment by shanejonas** [comment]
geth and the spec no longer support leading 0s

rel https://github.com/ethereum/execution-apis/issues/40#issuecomment-906400324
rel https://github.com/NomicFoundation/hardhat/issues/1585#issuecomment-906638245

**Comment by mcmire** [comment]
Closing this issue as it's just a question, but leaving this here for reference of course.
