### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by ochikov** [MetaMask/eth-json-rpc-filters#49]
Hello, since version 4.2.2 I am encountering a problem with webpack:

```
ERROR in ./~/eth-json-rpc-filters/~/pify/index.js
Module parse failed: /PathToProject/node_modules/eth-json-rpc-filters/node_modules/pify/index.js Unexpected token (44:2)
You may need an appropriate loader to handle this file type.
|               errorFirst: true,
|               promiseModule: Promise,
|               ...options
|       };
| 
 @ ./~/eth-json-rpc-filters/log-filter.js 8:11-26
 @ ./~/eth-json-rpc-filters/index.js
 @ ./~/web3-provider-engine/subproviders/filters.js
 @ ./~/@walletconnect/web3-provider/dist/cjs/index.js
 @ ./src/layouts/app-layout/AppLayout.js
 @ ./src/routes/index.js
 @ ./src/main.js
 @ multi ./src/main webpack-hot-middleware/client.js?path=/__webpack_hmr
```

**Comment by okwme** [comment]
bump

**Comment by mcmire** [comment]
Sorry for the late reply on this. If you are experiencing errors similar to this, then you want need to adjust your Webpack and/or Babel settings to match. My suggestion would be to use [`babel-preset-env`](https://babeljs.io/docs/en/babel-preset-env), which includes support for object spread via [the object spread proposal plugin](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread).
