### ISSUE TITLE
`eth_getFilterLogs` doesn't work

### ISSUE THREAD

**Issue by mcmire** [MetaMask/eth-json-rpc-filters#80]
I'm getting this when attempting to call `eth_getFilterLogs` through the extension:

```
MetaMask - RPC Error: results is not defined
```

I believe this is due to a missing `const` here: https://github.com/MetaMask/eth-json-rpc-filters/blob/5cbea3037b0655aa2c188d85b8ffe559a263dc0d/index.js?rgh-link-date=2022-12-14T22%3A35%3A20Z#L114

**Comment by Gudahtt** [comment]
Should be fixed by #84
